HTML/CSS & JavaScript capstone project
shm04/first-capstone-project pull request #1
Opened 2023-04-19 15:28 UTC by shm04

## HTML/CSS & JavaScript capstone project

### In this pull request I add the following changes:

#### - You should build only these 2 pages:

- The home page. ✔️ 
- The about page. ✔️ 

#### - Each of these pages should have versions for 2 different screen sizes:

- Mobile: up to 768px wide. ✔️ 
- Desktop: 768px or wider. ✔️ 

#### - Links
- The home page should have a link in the menu to the about page. ✔️ 
- The logo in the header links to the home page. ✔️ 

#### - Mobile menu
- When the user clicks (or taps) the hamburger button on the header, the mobile menu appears over the page.). ✔️ 
- The mobile menu should have a close (X) button that closes the menu. ✔️ 

#### - Dynamic page

- The section "Featured speakers" should be created dynamically in JavaScript. ✔️ 
- You should use a JavaScript variable with the data about the speakers and use it when the page loads to create the HTML for this section dynamically. ✔️

2023-04-19 19:06 UTC, cynthiainga requested changes
Hi @shm04, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlights

- [ ] No linters errors ✔️ 
- [ ] Correct GitHub flow ✔️ 
- [ ] Descriptive PR ✔️ 

## Required Changes ♻️

- [ ] Please kindly check the comments under the review 👇 👇 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-19 19:06 UTC, cynthiainga commented on style.css
> +  }
- [ ] Good job so far but the links are supposed to have `text-decoration: none`, please kindly fix that 🙃 😉 

Your design

<img width="922" alt="Screenshot 2023-04-19 at 20 23 15" src="https://user-images.githubusercontent.com/74501523/233152874-82be4498-3474-4fbd-869a-5c81485d1264.png">

Original design

<img width="987" alt="Screenshot 2023-04-19 at 20 22 48" src="https://user-images.githubusercontent.com/74501523/233152985-82df153b-fe10-4568-8dcd-0148ce053157.png">

2023-04-19 19:06 UTC, cynthiainga commented on index.html
> +        <h2 class="home-subtitle">"Hello! Rolling Loud community"</h2>
- [ ] This is a text normally so you are supposed to put it in the `<p>` tag instead of the `<hx>` tag for good practice, kindly fix that 😁 😬

2023-04-19 19:06 UTC, cynthiainga commented on index.html
> +        <h1 class="program-title">Main Program</h1>
- [ ] The whole html file has only one `<h1>` which is the title page and for other titles, you can put them in the`h2, h3,h4,...`, this is the HTML best practice 😁. Kindly fix that 🙃 🙃

2023-04-19 19:06 UTC, cynthiainga commented on index.html
> +        <h1 class="partner-title">Sponsors</h1>
- [ ] The whole html file has only one `<h1>` which is the title page and for other titles, you can put them in the `h2, h3,h4,...` this is the HTML best practice 😁. Kindly fix that 🙃 🙃

2023-04-19 19:06 UTC, cynthiainga commented on style.css
> +  }
- [ ] The website should be responsive and the min-width of the screen size for the desktop is `768px` which means at this point the desktop version designed should look good but look below your website on screen `768px` 🙃 🙃 

Your design

![shm04 github io_first-capstone-project_index html](https://user-images.githubusercontent.com/74501523/233161918-195b1bb0-93e7-45ea-80fc-e618af47e711.png)

- [ ] Please kindly fix that for the About page as well🙏 🙏

2023-04-19 19:06 UTC, cynthiainga commented on about.html
> +        <h2 class="home-subtitle">Hello! Rolling Loud community</h2>
- [ ]  This is a text normally so you are supposed to put it in the `<p>` tag instead of the `<hx>` tag for good practice, kindly fix that 😁 😬

2023-04-19 19:06 UTC, cynthiainga commented on about.html
> +        <h1 class="creative-past-title">Creative Commons<br>Global Summit 2015 Logo</h1>
- [ ] The whole html file has only one `<h1>` which is the title page and for other titles, you can put them in the `h2, h3,h4,...`, this is the HTML best practice 😁. Kindly fix that 🙃 🙃
- [ ] Also fix that for all the `<h1>` present in this file 😁 😁

2023-04-19 19:06 UTC, cynthiainga commented on about.html
> +    </section>
- [ ] In this section contain a line of text, and two images with text centered over them but I didn’t see the image. Pay attention, is not supposed to be a background image but an image, it's a part of the HTML. Please kindly fix that 🙏 🙏

2023-04-19 19:06 UTC, cynthiainga commented on style-about.css
> +}
- [ ] Please kindly make sure your design is correct, the mobile version is from `375px` to `767px` and the design should be good we can accept a broken design under `375px`; the web should be responsive 🙃. Take a look below 👇 

Your design

<img width="389" alt="Screenshot 2023-04-19 at 21 26 43" src="https://user-images.githubusercontent.com/74501523/233168236-08bd743d-2144-4b55-8caa-9ba715aee29c.png">

Original design

<img width="458" alt="Screenshot 2023-04-19 at 21 26 10" src="https://user-images.githubusercontent.com/74501523/233168535-a36dbee1-0777-46bb-9d07-892f6301a9e2.png">

2023-04-19 19:06 UTC, cynthiainga commented on style-about.css
> +}
- [ ] Please kindly make sure your design is correct, the mobile version is from `375px` to `767px` and the design should be good we can accept a broken design under `375px`; the web should be responsive 🙃. Take a look below 👇 

Your design

<img width="387" alt="Screenshot 2023-04-19 at 21 39 30" src="https://user-images.githubusercontent.com/74501523/233170373-f653e686-67c2-48e8-8223-d044190e13ab.png">

Original design

<img width="447" alt="Screenshot 2023-04-19 at 21 39 57" src="https://user-images.githubusercontent.com/74501523/233170460-d90d3bea-a020-4828-bf76-efae4ef112aa.png">

2023-04-19 19:06 UTC, cynthiainga commented on style.css
> +}
- [ ] Please kindly fix the menu design, the position should be `fixed` then the menu should cover the page... It should be almost the same as in the figma design but the color or background, the position of the closing menu can change. Take a look 👇 👇 

Your design

> |     | Home page                      | About page                      |     |
> | --- | ----------------------------------- | ------------------------------------ | --- |
> |     | <img width="326" alt="Screenshot 2023-04-19 at 22 00 48" src="https://user-images.githubusercontent.com/74501523/233174353-7b606535-226d-4b79-b7e6-e14f7f63577e.png"> | <img width="386" alt="Screenshot 2023-04-19 at 21 47 01" src="https://user-images.githubusercontent.com/74501523/233173198-4851df29-2bb0-4636-adaf-463268e7ea56.png"> |

An example of how the menu should look

<img width="386" alt="Screenshot 2023-04-19 at 21 54 19" src="https://user-images.githubusercontent.com/74501523/233173294-ca1f97d8-1b99-42d3-94b7-08fc4fd1df36.png">

2023-04-20 21:28 UTC, joskalenda requested changes
| STATUS: REQUIRED CHANGES ♻️  |
|--------------------------------|
| Hi @shm04 , |
|Great work on making the changes requested by a previous reviewer 👏, You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet. |
| <img src="https://media4.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif"/> |

## Highlights

- [ ].. ✅ Green linters
- [ ].. ✅ Great design
- [ ].. ✅ Good readme file

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-20 21:28 UTC, joskalenda commented on style.css
> +.artist-img {
- [ ] As mentioned by the previous reviewer, your nav menu 'style is a bit different from the original one, you should make some changes to match the design as she showed you and request for a next review, the other things were fixed correctly, congratulations

YOUR DESIGN

<img width="437" alt="1" src="https://user-images.githubusercontent.com/77843050/233491258-80c4fe7c-b5ef-484e-9dfd-a482f6555d39.png">


figma

<img width="386" alt="1" src="https://user-images.githubusercontent.com/77843050/233491401-1c832d9d-8168-42e2-a4aa-28ada14b1945.png">

2023-04-20 22:57 UTC, Favourezeugwa approved these changes
## STATUS: APPROVED 🥇 🏆 🍹 

Hi @shm04,

I am Favour 👩🏽 , your reviewer for this capstone project.

Great job implementing all the required changes. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Yayyy! 💃🏽, Congratulations! 🎉 🎉🎉

![happy](https://user-images.githubusercontent.com/99246359/202491301-53f8c6a2-8ff4-4337-9b6b-9c75c8bdf345.gif)

## Highlights 💯 
- No Linter errors ✔️
- Good commit messages ✔️
- Professional Readme file ✔️
- Descriptive PR ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-21 14:31 UTC, merged